In [1]:
import numpy as np

## Membuat array menggunakan list Python

Membuat array atau matrix dapat menggunakan fungsi bawaan python, yaitu `list`. Namun hal ini tidak disarankan di dalam pembuatan kode program untuk operasi aritmatika, karena hasil yang akan didapat nantinya tidak akan sesuai dengan yang diharapkan. Maka dari itu jika ingin melakukan operasi aritmatika pada matrix akan lebih baik menggunakan fungsi yang telah ada pada library Numpy.

In [2]:
arr_list = [0,1,2,3,4,5,6]
arr_list

[0, 1, 2, 3, 4, 5, 6]

In [3]:
type(arr_list)

list

## Membuat matrix menggunakan fungsi pada Numpy

Ada banyak fungsi pada Numpy yang dapat digunakan untuk membuat matrix, namun pada pembelajaran kali ini hanya disinggung beberapa saja, diantaranya yaitu array(), empty(), zeros(), ones(). Jika ingin mengetahui lebih lengkap bisa berkunjung ke dokumentasi Numpy pada link berikut : https://numpy.org/doc/

In [4]:
arr_numpy = np.array([1,2,3,4,5,6,7,8,9])
arr_numpy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr_kosong = np.empty(2)
arr_kosong

array([-6.33966994e-209, -2.57093007e+010])

In [6]:
arr_nol = np.zeros([2,2], dtype=int)
arr_nol

array([[0, 0],
       [0, 0]])

In [7]:
arr_satu = np.ones([3,3])
arr_satu

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
arr_satu2 = np.ones([2,3,2], dtype=int)
arr_satu2

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

## Reshape matrix

Kita bisa mengubah ukuran matrix sesuai dengan yang kita inginkan. Namun ada beberapa hal yang perlu diperhatikan, tidak boleh sembarangan. Syarat mengubah ukuran matrix adalah tidak boleh mengubah data / nilai yang ada pada matrix aslinya. Untuk lebih jelasnya bisa diperhatikan source code dibawah ini.

In [9]:
arr_reshape = np.arange(10)
arr_reshape

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr_reshape.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [11]:
arr_reshape.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
arr_reshape2 = np.arange(12)
arr_reshape2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
arr_reshape2.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
arr_reshape2.reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

## Interval matrix

Kita bisa membuat sebuah matrix dengan interval atau gap atau jarak sesuai dengan yang kita inginkan. Parameter ketiga merupakan gap yang kita buat untuk menentukan jarak antar nilai. Untuk lebih jelasnya bisa diperhatikan source code dibawah ini.

In [15]:
arr_inter = np.arange(1, 9, 2)
arr_inter

array([1, 3, 5, 7])

In [16]:
arr_inter2 = np.arange(4, 20, 2.5)
arr_inter2

array([ 4. ,  6.5,  9. , 11.5, 14. , 16.5, 19. ])

## Sequence matrix

Kita juga bisa menentukan berapa jumlah nilai yang terdapat dalam sebuah matrix menggunakan fungsi `linspace()`. Julah nilai defaultnya adalah 50, namun kita bisa mengubah jumlah nilai tersebut sesuai dengan yang kita inginkan. Untuk lebih jelasnya bisa diperhatikan source code dibawah ini.

In [17]:
arr_seq = np.linspace(2, 10)
arr_seq

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [18]:
arr_seq2 = np.linspace(2, 10, 5, dtype=int , retstep=True)
arr_seq2

(array([ 2,  4,  6,  8, 10]), 2.0)