In [1]:
import numpy as np

# Menggunakan fungsi `reshape()`

Contoh 1 :

In [2]:
data1 = np.arange(10)
data1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
data1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

Contoh 2 :

In [4]:
data1 = np.arange(12)
data1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
data1.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
data1.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

# Menggunakan fungsi `transpose()`

Contoh 1 :

In [7]:
data2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
data2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
data2.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

# Menggunakan fungsi `ravel()`

Contoh 1 :

In [9]:
data3 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
data3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
data3.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])