In [1]:
import numpy as np

Contoh 1 :

In [2]:
arr1 = np.linspace(-4, 4, 9, dtype=int)
arr1

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [3]:
arr2 = np.linspace(-5, 5, 11, dtype=int)
arr2

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [4]:
arr1, arr2 = np.meshgrid(arr1, arr2)

In [5]:
arr1

array([[-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [6]:
arr2

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5]])

Contoh 2 :

In [7]:
x = np.array([91, 92])
y = np.array([85, 86, 87, 88, 89])

In [8]:
x

array([91, 92])

In [9]:
y

array([85, 86, 87, 88, 89])

In [10]:
x, y = np.meshgrid(x, y)

In [11]:
x

array([[91, 92],
       [91, 92],
       [91, 92],
       [91, 92],
       [91, 92]])

In [12]:
y

array([[85, 85],
       [86, 86],
       [87, 87],
       [88, 88],
       [89, 89]])

Contoh 3 :

Dengan menggunakan matrix 2D

In [13]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [14]:
b = np.array([
    [11,12,13]
])

In [15]:
b, a = np.meshgrid(b,a)

In [16]:
b

array([[11, 12, 13],
       [11, 12, 13],
       [11, 12, 13],
       [11, 12, 13],
       [11, 12, 13],
       [11, 12, 13],
       [11, 12, 13],
       [11, 12, 13],
       [11, 12, 13]])

In [17]:
a

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6],
       [7, 7, 7],
       [8, 8, 8],
       [9, 9, 9]])