In [1]:
import numpy as np

# No Copy (Assignment)

In [2]:
arr = np.array([2,4,6,8])
arr

array([2, 4, 6, 8])

In [3]:
nc = arr
nc

array([2, 4, 6, 8])

In [4]:
arr[1] = 10

In [5]:
arr

array([ 2, 10,  6,  8])

In [6]:
nc

array([ 2, 10,  6,  8])

# View

In [7]:
arr = np.array([1,3,5,7])
arr

array([1, 3, 5, 7])

In [8]:
lihat = arr.view()
lihat

array([1, 3, 5, 7])

In [9]:
arr[3] = 11

In [10]:
arr

array([ 1,  3,  5, 11])

In [11]:
lihat

array([ 1,  3,  5, 11])

# Copy

In [12]:
arr = np.arange(0, 12, 2)
arr

array([ 0,  2,  4,  6,  8, 10])

In [13]:
salin = arr.copy()
salin

array([ 0,  2,  4,  6,  8, 10])

In [14]:
arr[0] = 14

In [15]:
arr

array([14,  2,  4,  6,  8, 10])

In [16]:
salin

array([ 0,  2,  4,  6,  8, 10])