In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,5,6,3])
arr

array([1, 2, 5, 6, 3])

In [3]:
arr = np.append(arr, 7)
arr

array([1, 2, 5, 6, 3, 7])

In [4]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [5]:
arr2 = np.array([4,5,6,7])
arr2

array([4, 5, 6, 7])

In [6]:
arr = np.append(arr1, arr2)
arr

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
arr_baris1 = np.arange(1,9).reshape(2,4)
arr_baris1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr_baris2 = np.arange(4,8).reshape(1,4)
arr_baris2

array([[4, 5, 6, 7]])

In [9]:
arr_baris = np.append(arr_baris1, arr_baris2, axis=0)
arr_baris

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 5, 6, 7]])

In [10]:
hehe = np.arange(1,4).reshape(3,1)
hehe

array([[1],
       [2],
       [3]])

In [11]:
arr_baris_hasil = np.append(arr_baris, hehe, axis=1)
arr_baris_hasil

array([[1, 2, 3, 4, 1],
       [5, 6, 7, 8, 2],
       [4, 5, 6, 7, 3]])

In [12]:
arr_kolom = np.arange(1,3).reshape(2,1)
arr_kolom

array([[1],
       [2]])

In [13]:
arr_kolom_hasil = np.append(arr_baris1, arr_kolom, axis=1)
arr_kolom_hasil

array([[1, 2, 3, 4, 1],
       [5, 6, 7, 8, 2]])