In [1]:
import numpy as np

# Indexing

In [2]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [3]:
arr1[1]

2

# Slicing

In [4]:
arr2 = np.array([1, 2, 3, 4, 5, 6])
arr2

array([1, 2, 3, 4, 5, 6])

In [5]:
arr2[1:4]

array([2, 3, 4])