In [1]:
import numpy as np

# Sorting

Sorting merupakan salah satu tahapan dalam pengurutan matrix. Menggunakan fungsi sort() sebuah matrix bisa diurutkan menurut baris dan kolom.

In [2]:
a = np.array([
    [12, 8],
    [10, 1]
])
a

array([[12,  8],
       [10,  1]])

In [3]:
arr1 = np.sort(a, axis=0)
arr1

array([[10,  1],
       [12,  8]])

In [4]:
arr2 = np.sort(a, axis=-1)
arr2

array([[ 8, 12],
       [ 1, 10]])

In [5]:
arr3 = np.sort(a, axis=1)
arr3

array([[ 8, 12],
       [ 1, 10]])

In [6]:
arr4 = np.sort(a, axis=None)
arr4

array([ 1,  8, 10, 12])

In [7]:
b = np.array([6,2,3,4,5,3,1,9])
b

array([6, 2, 3, 4, 5, 3, 1, 9])

In [8]:
arr1 = np.argsort(b)
arr1

array([6, 1, 2, 5, 3, 4, 0, 7], dtype=int64)

In [9]:
c = np.zeros(len(b), dtype=int)
c

array([0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
for i in range(0, len(b)):
    c[i] = b[arr1[i]]
c

array([1, 2, 3, 3, 4, 5, 6, 9])

In [11]:
for (i, j) in zip(b, c):
    print(i, " ", j)

6   1
2   2
3   3
4   3
5   4
3   5
1   6
9   9


In [12]:
arr2 = np.lexsort((c, b))
arr2

array([6, 1, 2, 5, 3, 4, 0, 7], dtype=int64)