In [1]:
import numpy as np

# Penjumlahan

In [6]:
arr1 = np.arange(0,11,2)
arr1

array([ 0,  2,  4,  6,  8, 10])

In [7]:
arr1+5

array([ 5,  7,  9, 11, 13, 15])

# Pengurangan

In [8]:
arr2 = np.arange(1,12,2)
arr2

array([ 1,  3,  5,  7,  9, 11])

In [9]:
arr2-3

array([-2,  0,  2,  4,  6,  8])

# Perkalian

In [11]:
arr3 = np.arange(1,6)
arr3

array([1, 2, 3, 4, 5])

In [12]:
arr3*10

array([10, 20, 30, 40, 50])

# Pembagian

In [13]:
arr4 = np.arange(5,10)
arr4

array([5, 6, 7, 8, 9])

In [14]:
arr4/2

array([2.5, 3. , 3.5, 4. , 4.5])